#!/usr/bin/env python3
"""Regenerate skill_lens/rules/core/CHANGELOG.md from pack.yaml (§15).

pack.yaml is the MACHINE truth for pack history; CHANGELOG.md is its
deterministic human mirror (release-notes source). CI runs this script and
demands ``git diff --exit-code`` on it — a hand-edited or stale mirror
fails the rule-pack workflow.

Deterministic: sorted nothing (changelog order is authored), no wall-clock,
byte-stable output. Exit 0 on success, 2 on structural failure.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from skill_lens.rules import load_core_pack  # noqa: E402

OUT_PATH = REPO_ROOT / "skill_lens" / "rules" / "core" / "CHANGELOG.md"

HEADER = (
    "# Core rule pack changelog\n"
    "\n"
    "<!-- GENERATED by scripts/pack_changelog.py from pack.yaml — do not\n"
    "     hand-edit. CI regenerates and demands a clean diff. Version\n"
    "     semantics are SPEC §15: new rule = patch; weight/severity change =\n"
    "     minor + rationale; deprecation ships >=2 minors before removal. -->\n"
)


def render() -> str:
    pack = load_core_pack()
    lines = [HEADER, f"Current version: **{pack.version}** · {len(pack.rules)} rules\n"]
    for entry in pack.changelog:
        version = str(entry.get("version", "?"))
        date = str(entry.get("date", ""))
        title = f"## {version}"
        if date:
            title += f" — {date}"
        lines.append(title)
        lines.append("")
        notes = entry.get("notes") or []
        if isinstance(notes, str):
            notes = [notes]
        for note in notes:
            text = " ".join(str(note).split())
            lines.append(f"- {text}")
        rationale = entry.get("rationale")
        if rationale:
            if isinstance(rationale, str):
                rationale = [rationale]
            lines.append("")
            lines.append("Rationale:")
            for item in rationale:
                lines.append(f"  - {' '.join(str(item).split())}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    try:
        OUT_PATH.write_text(render(), encoding="utf-8")
    except Exception as exc:  # noqa: BLE001 — one honest failure line
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
